/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.roster.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.liferay.roster.model.Roster;
import com.liferay.roster.service.RosterLocalService;
import com.liferay.roster.service.persistence.ClubPersistence;
import com.liferay.roster.service.persistence.RosterMemberPersistence;
import com.liferay.roster.service.persistence.RosterPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the roster local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.roster.service.impl.RosterLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.roster.service.impl.RosterLocalServiceImpl
 * @see com.liferay.roster.service.RosterLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class RosterLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements RosterLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.roster.service.RosterLocalServiceUtil} to access the roster local service.
	 */

	/**
	 * Adds the roster to the database. Also notifies the appropriate model listeners.
	 *
	 * @param roster the roster
	 * @return the roster that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Roster addRoster(Roster roster) {
		roster.setNew(true);

		return rosterPersistence.update(roster);
	}

	/**
	 * Creates a new roster with the primary key. Does not add the roster to the database.
	 *
	 * @param rosterId the primary key for the new roster
	 * @return the new roster
	 */
	@Override
	public Roster createRoster(long rosterId) {
		return rosterPersistence.create(rosterId);
	}

	/**
	 * Deletes the roster with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param rosterId the primary key of the roster
	 * @return the roster that was removed
	 * @throws PortalException if a roster with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Roster deleteRoster(long rosterId) throws PortalException {
		return rosterPersistence.remove(rosterId);
	}

	/**
	 * Deletes the roster from the database. Also notifies the appropriate model listeners.
	 *
	 * @param roster the roster
	 * @return the roster that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Roster deleteRoster(Roster roster) {
		return rosterPersistence.remove(roster);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Roster.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rosterPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.roster.model.impl.RosterModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return rosterPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.roster.model.impl.RosterModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return rosterPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rosterPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return rosterPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Roster fetchRoster(long rosterId) {
		return rosterPersistence.fetchByPrimaryKey(rosterId);
	}

	/**
	 * Returns the roster with the primary key.
	 *
	 * @param rosterId the primary key of the roster
	 * @return the roster
	 * @throws PortalException if a roster with the primary key could not be found
	 */
	@Override
	public Roster getRoster(long rosterId) throws PortalException {
		return rosterPersistence.findByPrimaryKey(rosterId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(com.liferay.roster.service.RosterLocalServiceUtil.getService());
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Roster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("rosterId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(com.liferay.roster.service.RosterLocalServiceUtil.getService());
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Roster.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("rosterId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(com.liferay.roster.service.RosterLocalServiceUtil.getService());
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Roster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("rosterId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return rosterLocalService.deleteRoster((Roster)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return rosterPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rosters.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.roster.model.impl.RosterModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of rosters
	 * @param end the upper bound of the range of rosters (not inclusive)
	 * @return the range of rosters
	 */
	@Override
	public List<Roster> getRosters(int start, int end) {
		return rosterPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rosters.
	 *
	 * @return the number of rosters
	 */
	@Override
	public int getRostersCount() {
		return rosterPersistence.countAll();
	}

	/**
	 * Updates the roster in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param roster the roster
	 * @return the roster that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Roster updateRoster(Roster roster) {
		return rosterPersistence.update(roster);
	}

	/**
	 * Returns the club local service.
	 *
	 * @return the club local service
	 */
	public com.liferay.roster.service.ClubLocalService getClubLocalService() {
		return clubLocalService;
	}

	/**
	 * Sets the club local service.
	 *
	 * @param clubLocalService the club local service
	 */
	public void setClubLocalService(
		com.liferay.roster.service.ClubLocalService clubLocalService) {
		this.clubLocalService = clubLocalService;
	}

	/**
	 * Returns the club persistence.
	 *
	 * @return the club persistence
	 */
	public ClubPersistence getClubPersistence() {
		return clubPersistence;
	}

	/**
	 * Sets the club persistence.
	 *
	 * @param clubPersistence the club persistence
	 */
	public void setClubPersistence(ClubPersistence clubPersistence) {
		this.clubPersistence = clubPersistence;
	}

	/**
	 * Returns the roster local service.
	 *
	 * @return the roster local service
	 */
	public RosterLocalService getRosterLocalService() {
		return rosterLocalService;
	}

	/**
	 * Sets the roster local service.
	 *
	 * @param rosterLocalService the roster local service
	 */
	public void setRosterLocalService(RosterLocalService rosterLocalService) {
		this.rosterLocalService = rosterLocalService;
	}

	/**
	 * Returns the roster persistence.
	 *
	 * @return the roster persistence
	 */
	public RosterPersistence getRosterPersistence() {
		return rosterPersistence;
	}

	/**
	 * Sets the roster persistence.
	 *
	 * @param rosterPersistence the roster persistence
	 */
	public void setRosterPersistence(RosterPersistence rosterPersistence) {
		this.rosterPersistence = rosterPersistence;
	}

	/**
	 * Returns the roster member local service.
	 *
	 * @return the roster member local service
	 */
	public com.liferay.roster.service.RosterMemberLocalService getRosterMemberLocalService() {
		return rosterMemberLocalService;
	}

	/**
	 * Sets the roster member local service.
	 *
	 * @param rosterMemberLocalService the roster member local service
	 */
	public void setRosterMemberLocalService(
		com.liferay.roster.service.RosterMemberLocalService rosterMemberLocalService) {
		this.rosterMemberLocalService = rosterMemberLocalService;
	}

	/**
	 * Returns the roster member persistence.
	 *
	 * @return the roster member persistence
	 */
	public RosterMemberPersistence getRosterMemberPersistence() {
		return rosterMemberPersistence;
	}

	/**
	 * Sets the roster member persistence.
	 *
	 * @param rosterMemberPersistence the roster member persistence
	 */
	public void setRosterMemberPersistence(
		RosterMemberPersistence rosterMemberPersistence) {
		this.rosterMemberPersistence = rosterMemberPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.roster.model.Roster",
			rosterLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.roster.model.Roster");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RosterLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Roster.class;
	}

	protected String getModelClassName() {
		return Roster.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = rosterPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.roster.service.ClubLocalService.class)
	protected com.liferay.roster.service.ClubLocalService clubLocalService;
	@BeanReference(type = ClubPersistence.class)
	protected ClubPersistence clubPersistence;
	@BeanReference(type = com.liferay.roster.service.RosterLocalService.class)
	protected RosterLocalService rosterLocalService;
	@BeanReference(type = RosterPersistence.class)
	protected RosterPersistence rosterPersistence;
	@BeanReference(type = com.liferay.roster.service.RosterMemberLocalService.class)
	protected com.liferay.roster.service.RosterMemberLocalService rosterMemberLocalService;
	@BeanReference(type = RosterMemberPersistence.class)
	protected RosterMemberPersistence rosterMemberPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}