/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.roster.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Club service. Represents a row in the &quot;ROSTER_Club&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.roster.model.impl.ClubModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.roster.model.impl.ClubImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Club
 * @see com.liferay.roster.model.impl.ClubImpl
 * @see com.liferay.roster.model.impl.ClubModelImpl
 * @generated
 */
@ProviderType
public interface ClubModel extends BaseModel<Club> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a club model instance should use the {@link Club} interface instead.
	 */

	/**
	 * Returns the primary key of this club.
	 *
	 * @return the primary key of this club
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this club.
	 *
	 * @param primaryKey the primary key of this club
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this club.
	 *
	 * @return the uuid of this club
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this club.
	 *
	 * @param uuid the uuid of this club
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the club ID of this club.
	 *
	 * @return the club ID of this club
	 */
	public long getClubId();

	/**
	 * Sets the club ID of this club.
	 *
	 * @param clubId the club ID of this club
	 */
	public void setClubId(long clubId);

	/**
	 * Returns the create date of this club.
	 *
	 * @return the create date of this club
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this club.
	 *
	 * @param createDate the create date of this club
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this club.
	 *
	 * @return the modified date of this club
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this club.
	 *
	 * @param modifiedDate the modified date of this club
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this club.
	 *
	 * @return the name of this club
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this club.
	 *
	 * @param name the name of this club
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.roster.model.Club club);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.roster.model.Club> toCacheModel();

	@Override
	public com.liferay.roster.model.Club toEscapedModel();

	@Override
	public com.liferay.roster.model.Club toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}