/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.roster.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.liferay.roster.model.RosterMember;
import com.liferay.roster.model.RosterMemberModel;
import com.liferay.roster.model.RosterMemberSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RosterMember service. Represents a row in the &quot;ROSTER_RosterMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RosterMemberModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RosterMemberImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RosterMemberImpl
 * @see RosterMember
 * @see RosterMemberModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RosterMemberModelImpl extends BaseModelImpl<RosterMember>
	implements RosterMemberModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a roster member model instance should use the {@link RosterMember} interface instead.
	 */
	public static final String TABLE_NAME = "ROSTER_RosterMember";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "rosterMemberId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "rosterId", Types.BIGINT },
			{ "contactId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rosterMemberId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("rosterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contactId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table ROSTER_RosterMember (uuid_ VARCHAR(75) null,rosterMemberId LONG not null primary key,createDate DATE null,modifiedDate DATE null,rosterId LONG,contactId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ROSTER_RosterMember";
	public static final String ORDER_BY_JPQL = " ORDER BY rosterMember.rosterMemberId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ROSTER_RosterMember.rosterMemberId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.roster.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.roster.model.RosterMember"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.roster.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.roster.model.RosterMember"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.roster.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.roster.model.RosterMember"),
			true);
	public static final long ROSTERID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;
	public static final long ROSTERMEMBERID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RosterMember toModel(RosterMemberSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RosterMember model = new RosterMemberImpl();

		model.setUuid(soapModel.getUuid());
		model.setRosterMemberId(soapModel.getRosterMemberId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setRosterId(soapModel.getRosterId());
		model.setContactId(soapModel.getContactId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RosterMember> toModels(RosterMemberSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RosterMember> models = new ArrayList<RosterMember>(soapModels.length);

		for (RosterMemberSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.roster.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.roster.model.RosterMember"));

	public RosterMemberModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _rosterMemberId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRosterMemberId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _rosterMemberId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RosterMember.class;
	}

	@Override
	public String getModelClassName() {
		return RosterMember.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("rosterMemberId", getRosterMemberId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("rosterId", getRosterId());
		attributes.put("contactId", getContactId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long rosterMemberId = (Long)attributes.get("rosterMemberId");

		if (rosterMemberId != null) {
			setRosterMemberId(rosterMemberId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long rosterId = (Long)attributes.get("rosterId");

		if (rosterId != null) {
			setRosterId(rosterId);
		}

		Long contactId = (Long)attributes.get("contactId");

		if (contactId != null) {
			setContactId(contactId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getRosterMemberId() {
		return _rosterMemberId;
	}

	@Override
	public void setRosterMemberId(long rosterMemberId) {
		_rosterMemberId = rosterMemberId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getRosterId() {
		return _rosterId;
	}

	@Override
	public void setRosterId(long rosterId) {
		_columnBitmask |= ROSTERID_COLUMN_BITMASK;

		if (!_setOriginalRosterId) {
			_setOriginalRosterId = true;

			_originalRosterId = _rosterId;
		}

		_rosterId = rosterId;
	}

	public long getOriginalRosterId() {
		return _originalRosterId;
	}

	@JSON
	@Override
	public long getContactId() {
		return _contactId;
	}

	@Override
	public void setContactId(long contactId) {
		_contactId = contactId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RosterMember.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RosterMember toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RosterMember)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RosterMemberImpl rosterMemberImpl = new RosterMemberImpl();

		rosterMemberImpl.setUuid(getUuid());
		rosterMemberImpl.setRosterMemberId(getRosterMemberId());
		rosterMemberImpl.setCreateDate(getCreateDate());
		rosterMemberImpl.setModifiedDate(getModifiedDate());
		rosterMemberImpl.setRosterId(getRosterId());
		rosterMemberImpl.setContactId(getContactId());

		rosterMemberImpl.resetOriginalValues();

		return rosterMemberImpl;
	}

	@Override
	public int compareTo(RosterMember rosterMember) {
		long primaryKey = rosterMember.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RosterMember)) {
			return false;
		}

		RosterMember rosterMember = (RosterMember)obj;

		long primaryKey = rosterMember.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		RosterMemberModelImpl rosterMemberModelImpl = this;

		rosterMemberModelImpl._originalUuid = rosterMemberModelImpl._uuid;

		rosterMemberModelImpl._setModifiedDate = false;

		rosterMemberModelImpl._originalRosterId = rosterMemberModelImpl._rosterId;

		rosterMemberModelImpl._setOriginalRosterId = false;

		rosterMemberModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RosterMember> toCacheModel() {
		RosterMemberCacheModel rosterMemberCacheModel = new RosterMemberCacheModel();

		rosterMemberCacheModel.uuid = getUuid();

		String uuid = rosterMemberCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			rosterMemberCacheModel.uuid = null;
		}

		rosterMemberCacheModel.rosterMemberId = getRosterMemberId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			rosterMemberCacheModel.createDate = createDate.getTime();
		}
		else {
			rosterMemberCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			rosterMemberCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			rosterMemberCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		rosterMemberCacheModel.rosterId = getRosterId();

		rosterMemberCacheModel.contactId = getContactId();

		return rosterMemberCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", rosterMemberId=");
		sb.append(getRosterMemberId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", rosterId=");
		sb.append(getRosterId());
		sb.append(", contactId=");
		sb.append(getContactId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.roster.model.RosterMember");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rosterMemberId</column-name><column-value><![CDATA[");
		sb.append(getRosterMemberId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rosterId</column-name><column-value><![CDATA[");
		sb.append(getRosterId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactId</column-name><column-value><![CDATA[");
		sb.append(getContactId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RosterMember.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RosterMember.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _rosterMemberId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _rosterId;
	private long _originalRosterId;
	private boolean _setOriginalRosterId;
	private long _contactId;
	private long _columnBitmask;
	private RosterMember _escapedModel;
}