package com.liferay.ide.velocity.ui.editor.xml;

/**
 * DOCUMENT ME!
 * 
 * @version $Revision: 13 $
 * @author <a href="mailto:akmal.sarhan@gmail.com">Akmal Sarhan </a>
 */
public interface IHTMLConstants
{

    public static final int      NONE       = 0;
    public static final int      TEXT       = 1;
    public static final int      FOLDER     = 2;
    public static final int      ANCHOR     = 3;
    public static final String[] EMPTY_TAGS = { "AREA", "BASE", "BASEFONT", "BR", "COL", "FRAME", "HR", "IMG", "INPUT", "ISINDEX", "LINK", "META", "PARAM" };
    public static final String[] START_TAGS = {
            "A",
            "ADDRESS",
            "APPLET",
            "B",
            "BIG",
            "BLOCKQUOTE",
            "BODY",
            "CAPTION",
            "CENTER",
            "CITE",
            "CODE",
            "COL",
            "COLGROUP",
            "DD",
            "DFN",
            "DIR",
            "DIV",
            "DL",
            "DT",
            "EM",
            "FONT",
            "FORM",
            "FRAMESET",
            "H1",
            "H2",
            "H3",
            "H4",
            "H5",
            "H6",
            "HEAD",
            "HTML",
            "I",
            "KBD",
            "LI",
            "MAP",
            "MENU",
            "NOBR",
            "NOFRAMES",
            "OBJECT",
            "OL",
            "OPTION",
            "P",
            "PRE",
            "SAMP",
            "SCRIPT",
            "SELECT",
            "SMALL",
            "SPAN",
            "STRIKE",
            "S",
            "STRONG",
            "STYLE",
            "SUB",
            "SUP",
            "TABLE",
            "TD",
            "TEXTAREA",
            "TH",
            "TITLE",
            "TR",
            "TT",
            "U",
            "UL",
            "VAR"    };
    public static final String[] BLOCK_TAGS = {
	 
            "A",
            "APPLET",
            "AREA",
            "BASE",
            "BASEFONT",
            "BLOCKQUOTE",
            "BODY",
            "BR",
            "CAPTION",
            "CITE",
            "CODE",
            "DD",
            "DFN",
            "DIR",
            "DIV",
            "DL",
            "DT",
            "FORM",
            "FRAME",
            "FRAMESET",
            "H1",
            "H2",
            "H3",
            "H4",
            "H5",
            "H6",
            "HEAD",
            "HR",
            "HTML",
            "IMG",
            "INPUT",
            "ISINDEX",
            "LI",
            "LINK",
            "MAP",
            "MENU",
            "META",
            "NOBR",
            "NOFRAMES",
            "OBJECT",
            "OL",
            "OPTION",
            "P",
            "PARAM",
            "PRE",
            "SAMP",
            "SCRIPT",
            "SELECT",
            "STRIKE",
            "TABLE",
            "TD",
            "TEXTAREA",
            "TH",
            "TITLE",
            "TR",
            "UL"                           };
}
