package com.liferay.ide.portlet.vaadin.core.operation;

import java.util.*;
import com.liferay.ide.portlet.vaadin.core.operation.*;
import com.liferay.ide.portlet.core.operation.*;
import org.eclipse.jst.j2ee.internal.common.operations.*;

/**
 * Class generated by JET.
 *
 * @author Henri Sara
 */
@SuppressWarnings({"restriction","unused"})
public class VaadinPortletTemplate implements INewVaadinPortletClassDataModelProperties
{
  protected static String nl;
  public static synchronized VaadinPortletTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    VaadinPortletTemplate result = new VaadinPortletTemplate();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "package ";
  protected final String TEXT_2 = ";";
  protected final String TEXT_3 = NL;
  protected final String TEXT_4 = NL + "import ";
  protected final String TEXT_5 = NL + "public ";
  protected final String TEXT_6 = "abstract ";
  protected final String TEXT_7 = "final ";
  protected final String TEXT_8 = "class ";
  protected final String TEXT_9 = " extends ";
  protected final String TEXT_10 = " implements ";
  protected final String TEXT_11 = ", ";
  protected final String TEXT_12 = " {";
  protected final String TEXT_13 = NL + NL + "    /**" + NL + "     * Default constructor. " + NL + "     */" + NL + "    public ";
  protected final String TEXT_14 = "() {" + NL + "    }";
  protected final String TEXT_15 = NL + "       " + NL + "    /**" + NL + "     * @see ";
  protected final String TEXT_16 = "#";
  protected final String TEXT_17 = "(";
  protected final String TEXT_18 = ")" + NL + "     */" + NL + "    public ";
  protected final String TEXT_19 = ") {" + NL + "        super(";
  protected final String TEXT_20 = ");" + NL + "    }";
  protected final String TEXT_21 = NL + NL + "\t/**" + NL + "     * @see ";
  protected final String TEXT_22 = " ";
  protected final String TEXT_23 = ") {" + NL + "        // TODO Auto-generated method stub";
  protected final String TEXT_24 = NL + "\t\t\treturn ";
  protected final String TEXT_25 = NL + "    }";
  protected final String TEXT_26 = NL + NL + "    public void init() {" + NL + "        Window window = new Window(\"Vaadin Portlet Application\");" + NL + "        setMainWindow(window);" + NL + "        window.addComponent(new Label(\"Hello Vaadin user!\"));" + NL + "    }" + NL + "" + NL + "}";

   public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
     CreateVaadinPortletTemplateModel model = (CreateVaadinPortletTemplateModel) argument; 
    
	model.removeFlags(CreateJavaEEArtifactTemplateModel.FLAG_QUALIFIED_SUPERCLASS_NAME); 

    
	if (model.getJavaPackageName() != null && model.getJavaPackageName().length() > 0) {

    stringBuffer.append(TEXT_1);
    stringBuffer.append( model.getJavaPackageName() );
    stringBuffer.append(TEXT_2);
    
	}

    stringBuffer.append(TEXT_3);
     
	Collection<String> imports = model.getImports();
	for (String anImport : imports) { 

    stringBuffer.append(TEXT_4);
    stringBuffer.append( anImport );
    stringBuffer.append(TEXT_2);
     
	}

    stringBuffer.append(TEXT_3);
    
	if (model.isPublic()) { 

    stringBuffer.append(TEXT_5);
     
	} 

	if (model.isAbstract()) { 

    stringBuffer.append(TEXT_6);
    
	}

	if (model.isFinal()) {

    stringBuffer.append(TEXT_7);
    
	}

    stringBuffer.append(TEXT_8);
    stringBuffer.append( model.getClassName() );
    
	String superClass = model.getSuperclassName();
 	if (superClass != null && superClass.length() > 0) {

    stringBuffer.append(TEXT_9);
    stringBuffer.append( superClass );
    
	}

	List<String> interfaces = model.getInterfaces(); 
 	if ( interfaces.size() > 0) { 

    stringBuffer.append(TEXT_10);
    
	}
	
 	for (int i = 0; i < interfaces.size(); i++) {
   		String INTERFACE = (String) interfaces.get(i);
   		if (i > 0) {

    stringBuffer.append(TEXT_11);
    
		}

    stringBuffer.append( INTERFACE );
    
	}

    stringBuffer.append(TEXT_12);
     
	if (!model.hasEmptySuperclassConstructor()) { 

    stringBuffer.append(TEXT_13);
    stringBuffer.append( model.getClassName() );
    stringBuffer.append(TEXT_14);
     
	} 

	if (model.shouldGenSuperclassConstructors()) {
		List<Constructor> constructors = model.getConstructors();
		for (Constructor constructor : constructors) {
			if (constructor.isPublic() || constructor.isProtected()) { 

    stringBuffer.append(TEXT_15);
    stringBuffer.append( model.getSuperclassName() );
    stringBuffer.append(TEXT_16);
    stringBuffer.append( model.getSuperclassName() );
    stringBuffer.append(TEXT_17);
    stringBuffer.append( constructor.getParamsForJavadoc() );
    stringBuffer.append(TEXT_18);
    stringBuffer.append( model.getClassName() );
    stringBuffer.append(TEXT_17);
    stringBuffer.append( constructor.getParamsForDeclaration() );
    stringBuffer.append(TEXT_19);
    stringBuffer.append( constructor.getParamsForCall() );
    stringBuffer.append(TEXT_20);
    
			} 
		} 
	} 

    
	if (model.shouldImplementAbstractMethods()) {
		for (Method method : model.getUnimplementedMethods()) { 

    stringBuffer.append(TEXT_21);
    stringBuffer.append( method.getContainingJavaClass() );
    stringBuffer.append(TEXT_16);
    stringBuffer.append( method.getName() );
    stringBuffer.append(TEXT_17);
    stringBuffer.append( method.getParamsForJavadoc() );
    stringBuffer.append(TEXT_18);
    stringBuffer.append( method.getReturnType() );
    stringBuffer.append(TEXT_22);
    stringBuffer.append( method.getName() );
    stringBuffer.append(TEXT_17);
    stringBuffer.append( method.getParamsForDeclaration() );
    stringBuffer.append(TEXT_23);
     
			String defaultReturnValue = method.getDefaultReturnValue();
			if (defaultReturnValue != null) { 

    stringBuffer.append(TEXT_24);
    stringBuffer.append( defaultReturnValue );
    stringBuffer.append(TEXT_2);
    
			} 

    stringBuffer.append(TEXT_25);
     
		}
	} 

    stringBuffer.append(TEXT_26);
    stringBuffer.append(TEXT_3);
    return stringBuffer.toString();
  }
}