<#include "../basetemplate.ftl">

<#include "../component.ftl">

public class ${classname} extends ${supperclass}<${simplemodelclass}> {

	@Override
	public void onBeforeCreate(${simplemodelclass} model) throws ModelListenerException {
		System.out.println(
			"About to create layout: " + model.getNameCurrentValue());

		model.setTitle("Title generated by model listener!");
	}
}