package sample.model.listener;

import com.liferay.portal.kernel.exception.ModelListenerException;
import com.liferay.portal.kernel.model.BaseModelListener;
import com.liferay.portal.kernel.model.Layout;
import com.liferay.portal.kernel.model.ModelListener;

import org.osgi.service.component.annotations.Component;

/**
 * @author Greg Amerson
 */
@Component(immediate = true, service = ModelListener.class)
public class CustomLayoutListener extends BaseModelListener<Layout> {

	@Override
	public void onBeforeCreate(Layout model) throws ModelListenerException {
		System.out.println(
			"About to create layout: " + model.getNameCurrentValue());

		model.setTitle("Title generated by model listener!");
	}

}